### ISSUE TITLE
Is there any way I can render the event generated calendar in my nativescript app?

### ISSUE THREAD

**Issue by dlucidone** [EddyVerbruggen/nativescript-calendar-demo#1]

**Comment by EddyVerbruggen** [comment]
?

**Comment by dlucidone** [comment]
I mean this kinda calendar rendering in my nativescript app. I need this kinda week view in my app in which i can create events and delete events.

![screen shot 2017-02-15 at 4 28 44 pm](https://cloud.githubusercontent.com/assets/9256365/22971506/e6a4ef94-f39b-11e6-8da1-fdfb4fb7bbf3.png)

**Comment by EddyVerbruggen** [comment]
That's not what's this plugin is about. It's for programmatic interaction with the Calendar.

For UI-based interaction [check this out](http://www.telerik.com/nativescript-ui/calendar).
